name: Build cicd dataops image
env:
  DBT_VERSION: "1.0.0"
  DATA_PIPELINES_CLI: "1.21.0"

on:
  branches:
    - main
  pull_request:

jobs:
  buildx-mlops:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx-dataops
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_DEPLOY_SA_KEY }}

      - name: Build cicd dataops image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            PLATFORM=${{ matrix.platform }}
          push: true
          tags: gcr.io/getindata-images-public/cicd-image:${{ matrix.platform }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache